### ISSUE TITLE
I cant reproduce example

### ISSUE THREAD

**Issue by sergeysova** [mikestopcontinues/postcss-custom-units#1]
I use Stylus and Webpack:

``` styl
header
  --unit-dp: 2px
  font-size: 6pd
```

But in css i have:

``` css
header {
  --unit-db: 2px;
  font-size: 6 dp;
}
```

> I use plugins: autoprefixer, postcss-short
